name: CD
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy info
        run: echo "Тут буде деплой, залежно від вибраної хмари (Fly.io, Render, Railway тощо)"